model:
  policy: "MultiInputPolicy"
  batch_size: 16
  learning_rate: 0.0003
  buffer_size: 100000
  learning_starts: 100
  train_freq: 4
  gradient_steps: 4
  ent_coef: "auto"
  target_update_interval: 1
  gamma: 0.99
  tau: 0.005
  verbose: 1

training:
  num_obstacles: 200
  model_inputs: ["point_cloud"] # This should be a non-empty subset of ["pose", "velocity", "steering", "depth", "point_cloud"]
  total_timesteps: 400
  num_envs: 4
  device: "cpu" # Change to "cuda" for Nvidia or "cpu" for CPU